# Generated by Django 4.2 on 2023-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prdid', models.IntegerField(primary_key=True, serialize=False)),
                ('prdname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
