# Generated by Django 4.2 on 2023-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
