# Generated by Django 4.2 on 2023-04-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0002_remove_employee_id_alter_employee_empno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhar_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=20)),
                ('aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ORM.aadhar')),
            ],
        ),
    ]
