# Generated by Django 4.2 on 2023-04-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0006_base2_base3_child1_child2_child3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base3',
        ),
        migrations.DeleteModel(
            name='Child1',
        ),
        migrations.RemoveField(
            model_name='child2',
            name='base2_ptr',
        ),
        migrations.DeleteModel(
            name='Child3',
        ),
        migrations.DeleteModel(
            name='Base2',
        ),
        migrations.DeleteModel(
            name='Child2',
        ),
    ]
