# Generated by Django 4.2 on 2023-04-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0007_delete_base3_delete_child1_remove_child2_base2_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
