# Generated by Django 4.2 on 2023-04-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0009_base2_child2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base3',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Child3',
            fields=[
            ],
            options={
                'ordering': ['-salary'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ORM.base3',),
        ),
    ]
