# Generated by Django 4.2 on 2023-04-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0010_base3_child3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child3',
            options={'ordering': ['salary']},
        ),
    ]
